<h2 class="title"><?php e($title) ?></h2>
<p>All posts on this blog, grouped by month of publication:</p>
<ul>
<?php $subtitle = false; ?> 
<?php foreach (array_keys($data) as $n=>$i): ?>
<?php $newtitle = date("F Y",strtotime($data[$i]['posts']['published'])); if (!$subtitle || $newtitle!=$subtitle): $subtitle = $newtitle; ?>
</ul>
<h3><?php e($subtitle); ?></h3>
<ul>
<?php endif; ?>
<li>
    <?php e(date("jS",strtotime($data[$i]['posts']['published'])));?>: 
    <a href="<?php e(urlencode($data[$i]['posts']['slug']));?>"><?php e($data[$i]['posts']['title']);?></a>
    <?php if (isset($stats['popular_posts'][$data[$i]['posts']['slug']])): ?>&#9733;<?php endif; ?>
</li>
<?php endforeach; ?>
</ul>
<p>&#9733; = popular post</p>