<h2>Dashboard</h2>
<table class="table">
  <thead>
    <tr>
      <th>Day</th>
      <th>Visitors</th>
      <th>Views</th>
      <th>Post</th>
    </tr>
  </thead>
  <tbody>
    <?php foreach ($stats['visitors'] as $stat): ?>
    <tr>
      <td><?php e(date("Y-m-d (D)",strtotime($stat['unique_visitors']['day'])));?></td>
      <td><?php e($stat['unique_visitors']['visitors']);?></td>
      <td><?php e($stat['unique_visitors']['views']);?></td>
      <td>
        <?php if (isset($stats['posts'][$stat['unique_visitors']['day']])): ?>
          <a href="<?php e($stats['posts'][$stat['unique_visitors']['day']]);?>"><?php e($stats['posts'][$stat['unique_visitors']['day']]);?></a>
        <?php endif; ?>
      </td>
    </tr>
    <?php endforeach; ?>
  </tbody>
</table>
