<h2>Dashboard</h2>
<div class="row">
<div class="col-md-6"><?php Buffer::get('daily_visitors_graph'); ?></div>
<div class="col-md-6"><?php Buffer::get('monthly_visitors_graph'); ?></div>
</div>
<div class="row">
<div class="col-md-6"><br/><?php Buffer::get('daily_homepage_hits_graph'); ?></div>
<div class="col-md-6"><br/><?php Buffer::get('monthly_homepage_hits_graph'); ?></div>
</div>
<div class="row">
<div class="col-md-6"><br/><?php Buffer::get('daily_subscribers_graph'); ?></div>
<div class="col-md-6"><br/><?php Buffer::get('monthly_subscribers_graph'); ?></div>
</div>
<div class="row">
<div class="col-md-6"><br/><?php Buffer::get('popular_posts_day_graph'); ?></div>
<div class="col-md-6"><br/><?php Buffer::get('popular_posts_month_graph'); ?></div>
</div>
<div class="row">
<div class="col-md-12">
<br/>
<table class="table">
  <thead>
    <tr>
      <th>Day</th>
      <th>Visitors</th>
      <th>Views</th>
      <th>Post</th>
    </tr>
  </thead>
  <tbody>
    <?php foreach ($stats['visitors_per_day'] as $stat): ?>
    <tr>
      <td><?php e($stat['unique_visitors']['day']);?></td>
      <td><?php e($stat['unique_visitors']['visitors']);?></td>
      <td><?php e($stat['unique_visitors']['views']);?></td>
      <td>
        <?php if (isset($stats['posts'][$stat['unique_visitors']['day']])): ?>
          <a href="<?php e($stats['posts'][$stat['unique_visitors']['day']]);?>"><?php e($stats['posts'][$stat['unique_visitors']['day']]);?></a>
        <?php endif; ?>
      </td>
    </tr>
    <?php endforeach; ?>
  </tbody>
</table>
</div>
</div>