<?php foreach (array_keys($data) as $n=>$i): ?>
<h2 class="title"><a href="<?php e(urlencode($data[$i]['posts']['slug']));?>"><?php e($data[$i]['posts']['title']);?></a></h2>
<p class="details"><?php e(date("d M Y",strtotime($data[$i]['posts']['published'])));?> - by '<?php e($data[$i]['users']['name']);?>'</p>
<?php Buffer::get("content[$i]"); ?>
<?php if ($data[$i]['posts']['more_html']): ?>
  <a href="<?php e(urlencode($data[$i]['posts']['slug']));?>">Continue reading...</a>
<?php endif; ?>
<hr class="continue"/>
<?php endforeach; ?>
