<h2 class="title"><a href="<?php e(urlencode($data['posts']['slug']));?>"><?php e($data['posts']['title']);?></a></h2>
<p class="details"><?php e(date("d M Y", strtotime($data['posts']['published'])));?> - by '<?php e($data['users']['name']);?>'</p>
<?php Buffer::get('content');?>
<hr class="continue"/>
<p>PS: Liked the article? Share it on
<a href="https://www.facebook.com/sharer/sharer.php?u=<?php e(rawurlencode($url));?>">Facebook,</a>
<a href="https://twitter.com/home?status=<?php e(rawurlencode($status));?>">Twitter,</a>
<a href="https://www.linkedin.com/shareArticle?mini=true&url=<?php e(rawurlencode($url));?>&title=<?php e(rawurlencode($title));?>&summary=&source=">LinkedIn or</a>
<a href="https://news.ycombinator.com/submitlink?u=<?php e(rawurlencode($url));?>&t=<?php e(rawurlencode($title));?>">Hacker News</a>!
<hr class="continue"/>
