<?php header('Content-Type: text/xml'); ?>
<?xml version="1.0" encoding="utf-8"?>
<rss version="2.0">
<channel>
<title><?php e($_SESSION['settings']['title']);?></title>
<link><?php e(Router::getBaseUrl());?></link>
<description><?php e($_SESSION['settings']['subtitle']);?></description>
<?php foreach (array_keys($data) as $n=>$i): ?>
<item>
  <title><?php e($data[$i]['posts']['title']);?></title>
  <link><?php e(Router::getBaseUrl().urlencode($data[$i]['posts']['slug']));?></link>
  <description></description>
  <pubDate><?php e(date("D, d M Y H:i:s O",strtotime($data[$i]['posts']['published'])));?></pubDate>
  <category></category>
  <source></source>
  <content:encoded><![CDATA[<?php Buffer::get("content[$i]"); ?>]]></content:encoded>
</item>
<?php endforeach; ?>
</channel>
</rss>
