<!DOCTYPE html>
<html>
  <head>
    <base href="<?php e(Router::getBaseUrl()); ?>">
    <title><?php e($title) ?></title>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="shortcut icon" href="img/favicon.ico">
    <link href="css/default.css" rel="stylesheet">
  </head>
  <body>
    <div class="menu">
        <h1><a href="/" style="color: gray; text-decoration:none;"><strong style="font-size: 300%;">TQ</strong><br/>dev.com</a></h1>
        <p><em>Blog about software development</em></p>
        <h3>Popular posts</h3>
        <ul>
          <?php foreach ($stats['popular_posts'] as $slug => $title): ?>
            <li><a href="<?php e($slug); ?>"><?php e($title); ?></a></li>
          <?php endforeach; ?>
        </ul>
        <h3>Latest posts</h3>
        <ul>
          <?php foreach ($stats['latest_posts'] as $slug => $title): ?>
            <li><a href="<?php e($slug); ?>"><?php e($title); ?></a></li>
          <?php endforeach; ?>
        </ul>
        <h3>Unique visitors</h3>
        <ul>
          <li>Now online: <?php e($stats['visitors_5_min']); ?></li>
          <li>Today: <?php e($stats['visitors_today']); ?></li>
          <li>This month: <?php e($stats['visitors_month']); ?></li>
        </ul>
    </div>
    <div class="body">
        <?php Buffer::get('html'); ?>
    </div>
    </body>
</html>
