<!DOCTYPE html>
<html lang="en">
  <head>
    <base href="<?php e(Router::getBaseUrl()); ?>">
    <title><?php e($title) ?></title>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="shortcut icon" href="img/favicon.ico">
    <link href="css/default.css" rel="stylesheet">
  </head>
  <body>
    <div class="header">
        <h1><a href="<?php e(Router::getBaseUrl()); ?>"><?php Buffer::get('title_html'); ?></h1>
        <p class="subtitle"><?php Buffer::get('subtitle_html'); ?></p>
        <p><a href="feed">Subscribe to RSS</a></p>
    </div>
    <div class="body">
        <?php Buffer::get('html'); ?>
    </div>
    <div class="sidebar">
        <h3>Popular posts</h3>
        <ul>
          <?php foreach ($stats['popular_posts'] as $slug => $title): ?>
            <li><a href="<?php e($slug); ?>"><?php e($title); ?></a></li>
          <?php endforeach; ?>
        </ul>
        <h3>Latest posts</h3>
        <ul>
          <?php foreach ($stats['latest_posts'] as $slug => $title): ?>
            <li><a href="<?php e($slug); ?>"><?php e($title); ?></a></li>
          <?php endforeach; ?>
        </ul>
        <h3>Unique visitors</h3>
        <ul>
          <li>Now online: <?php e($stats['visitors_5_min']); ?></li>
          <li>Today: <?php e($stats['visitors_today']); ?></li>
          <li>This month: <?php e($stats['visitors_month']); ?></li>
        </ul>
        <br/>
    </div>
    </body>
</html>
