<!DOCTYPE html>
<html>
  <head>
    <base href="<?php e(Router::getBaseUrl()); ?>">
    <title>MindaBlog</title>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="shortcut icon" href="img/favicon.ico">
    <link href="css/default.css" rel="stylesheet">
  </head>
  <body>
    <div class="menu">
    <p><img src="img/maurits.jpg" alt="Maurits van der Schee"/><br/>Maurits van der Schee</p>        
    <p>
      <a href="admin">Admin area</a><br/>
    </p>
  </div>
  <div class="body">
    <?php Buffer::get('html'); ?>
  </div>
</body>
</html>
