<!DOCTYPE html>
<html>
  <head>
    <base href="<?php e(Router::getBaseUrl()); ?>">
    <title>MindaBlog</title>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="shortcut icon" href="img/favicon.ico">
    <link href="css/default.css" rel="stylesheet">
  </head>
  <body>
    <?php Buffer::get('html'); ?>
    <p><a href="">Back to site</a></p>
  </body>
</html>
