<h2>Users</h2>
<table class="table">
  <thead>
    <tr>
      <th>Username</th>
      <th>Name</th>
      <th>Created</th>
    </tr>
  </thead>
  <tbody>
    <?php foreach ($rows as $row): ?>
    <tr>
      <td><?php e($row['users']['username']);?></td>
      <td><?php e($row['users']['name']);?></td>
      <td><?php e($row['users']['created']);?></td>
    </tr>
    <?php endforeach; ?>
  </tbody>
</table>

<p><a href="admin/users/add">Add user</a></p>
