<h2>View user</h2>
<table class="table">
  <tr><th>Username</th><td><?php e($data['users']['username']);?></td></tr>
  <tr><th>Name</th><td><?php e($data['users']['name']);?></td></tr>
  <tr><th>Created</th><td><?php e($data['users']['created']);?></td></tr>
  <tr><th># Posts</th><td><?php echo $postCount;?></td></tr>
</table>

<p><a class="btn btn-primary" href="admin/users/edit/<?php echo $id; ?>">Edit</a></p>
