<h2>New post</h2>
<form method="post">
	<div class="form-group">
	    <input class="form-control" name="title" type="text" placeholder="Title?" />
	</div>
    <div class="form-group">
		<textarea class="form-control" name="content" data-provide="markdown" rows="10"></textarea>
    </div>
    <div class="form-group">
    	<button class="btn btn-primary" type="submit">Save</button>
    </div>
</form> 