<?php Buffer::start('head'); ?>

	<!-- Markdown -->
    <script src="js/markdown.js"></script>

    <!-- Bootstrap Markdown -->
    <link href="css/bootstrap-markdown.min.css" rel="stylesheet" media="screen">
    <script src="js/bootstrap-markdown.js"></script>

    <!-- Bootstrap DatePicker -->
    <link href="css/bootstrap-datepicker.css" rel="stylesheet" media="screen">
    <script src="js/bootstrap-datepicker.js"></script>
    <script>
    // save with ctrl-s
    $(window).keypress(function(event) {
        if (!(event.which == 115 && event.ctrlKey) && !(event.which == 19)) return true;
        $("form button[type=submit]").click();
        event.preventDefault();
        return false;
    });
    </script>

<?php Buffer::end('head'); ?>
<div class="page-header">
  <h1>Edit post</h1>
</div>
<form method="post">
	<div class="form-group">
	    <label class="control-label" for="posts[published]">Published</label>
		<div class="input-group">
    		<input class="form-control" name="posts[published]" type="text" value="<?php e($_POST['posts']['published']); ?>" id="posts[published]" data-provide="datepicker" data-date-format="yyyy-mm-dd" data-date-today-highlight="1" data-date-autoclose="1">
    		<span class="input-group-addon"><i class="glyphicon glyphicon-th"></i></span>
    	</div>
	</div>
	<div class="form-group <?php e(isset($errors['posts[slug]'])?'has-error':'') ?>">
	    <label class="control-label" for="posts[slug]">Slug</label>
	    <div class="input-group">
          <div class="input-group-addon">/</div>
  		  <input class="form-control" name="posts[slug]" type="text" value="<?php e($_POST['posts']['slug']); ?>" id="posts[slug]" />
  		</div>
  		<span class="help-block"><?php if (isset($errors['posts[slug]'])) e($errors['posts[slug]']); ?></span>
	</div>
	<div class="form-group">
	    <label class="control-label" for="posts[title]">Title</label>
  		<input class="form-control" name="posts[title]" type="text" value="<?php e($_POST['posts']['title']); ?>" id="posts[title]" />
	</div>
	<div class="form-group">
		<label class="control-label" for="posts[content]">Content</label>
  		<textarea class="form-control" name="posts[content]" data-provide="markdown" rows="30" id="posts[content]"><?php e($_POST['posts']['content']); ?></textarea>
    </div>
    <div class="form-group">
    	<button class="btn btn-primary" type="submit">Save</button>
    </div>
	<?php Session::getCsrfInput(); ?>
</form>
