<?php echo Buffer::start('head'); ?>
    <!-- Markdown -->
    <script src="js/markdown.js"></script>
        
    <!-- Bootstrap Markdown -->
    <link href="css/bootstrap-markdown.min.css" rel="stylesheet" media="screen">
    <script src="js/bootstrap-markdown.js"></script>
<?php echo Buffer::end('head'); ?>
<h2>Edit post</h2>
<form method="post">
	<div class="form-group">
	    <label class="control-label" for="posts[title]">Title</label>
  		<input class="form-control" name="posts[title]" type="text" value="<?php e($_POST['posts']['title']); ?>" id="posts[title]" />
	</div>
	<div class="form-group <?php echo isset($errors['posts[slug]'])?'has-error':'' ?>">
	    <label class="control-label" for="posts[slug]">Slug</label>
  		<input class="form-control" name="posts[slug]" type="text" value="<?php e($_POST['posts']['slug']); ?>" id="posts[slug]" />
  		<span class="help-block"><?php if (isset($errors['posts[slug]'])) e($errors['posts[slug]']); ?></span>
	</div>
	<div class="form-group">
		<label class="control-label" for="posts[content]">Content</label>
  		<textarea class="form-control" name="posts[content]" data-provide="markdown" rows="10" id="posts[content]"><?php e($_POST['posts']['content']); ?></textarea>
    </div>
    <div class="form-group">
    	<button class="btn btn-primary" type="submit">Save</button>
    	<a class="btn btn-danger" href="admin/posts/delete/<?php echo $id; ?>">Delete</a>
	</div>
	<?php Session::getCsrfInput(); ?>
</form>
