<h2>Posts</h2>
<div class="list-group">
  <?php foreach ($rows as $row): ?>
    <a href="admin/posts/edit/<?php e($row['posts']['id']);?>" class="list-group-item">
      <span class="badge">42</span><span class="label label-warning" style="float:right; margin-right:5px;">Warning</span>
      <h4 class="list-group-item-heading"><?php e($row['posts']['title']);?> <small>/<?php e($row['posts']['slug']);?></small></h4>
      <p class="list-group-item-text">
        <?php e($row['posts']['published']?:'draft');?> by "<?php e($row['users']['username']);?>".
      </p>
    </a>
  <?php endforeach; ?>
</div>
<p><a class="btn btn-primary" href="admin/posts/add">Add</a></p>
