<h2>Posts</h2>
<table class="table">
  <thead>
    <tr>
      <th>Title</th>
      <th>Author</th>
      <th>Tags</th>
      <th>Date</th>
    </tr>
  </thead>
  <tbody>
    <?php foreach ($rows as $row): ?>
    <tr>
      <td><a href="admin/posts/edit/<?php e($row['posts']['id']);?>"><?php e($row['posts']['title']);?></a></td>
      <td><a href="admin/users/view/<?php e($row['users']['id']);?>"><?php e($row['users']['username']);?></a></td>
      <td><?php e($row['posts']['tags']);?></td>
      <td><?php e($row['posts']['published']?:'draft');?></td>
    </tr>
    <?php endforeach; ?>
  </tbody>
</table>

<p><a class="btn btn-primary" href="admin/posts/add">Add</a></p>
