<h2 class="title"><a href="<?php e(urlencode($data['posts']['slug']));?>"><?php e($data['posts']['title']);?></a></h2>
<p class="details"><?php e(date("d M Y",strtotime($data['posts']['published'])));?> - by '<?php e($data['users']['name']);?>'</p>
<?php Buffer::get("content_html"); ?>
<?php if ($data['posts']['more_html']): ?>
  <hr/>
<?php endif; ?>

<?php Buffer::get('content'); ?>
<hr class="continue"/>